// Autogenerated by mkresource.pl, do not edit
package de.theiling.neatlauncher

const val back_opaq = 0
const val back_tluc = 1
const val back_tpar = 2
const val color_achr = 0
const val color_ambr = 1
const val color_pump = 2
const val color_redx = 3
const val color_lila = 4
const val color_blue = 5
const val color_cyan = 6
const val date_syst = 0
const val date_none = 1
const val date_yyyy = 2
const val date_EEEy = 3
const val date_EEEE = 4
const val font_sans = 0
const val font_seri = 1
const val font_mono = 2
const val font_curs = 3
const val font_ubun = 4
const val time_syst = 0
const val time_none = 1
const val time_Hmmx = 2
const val time_HHmm = 3
const val time_hmma = 4
const val time_hhma = 5
const val time_anlg = 6
const val time_word = 7
const val time_grid = 8
