// Autogenerated by mkresource.pl, do not edit
package de.theiling.neatlauncher

fun selectTheme(back: Int, font: Int, color: Int) = when (back) {
    back_tluc -> when (font) {
        font_seri -> when (color) {
            color_ambr -> R.style.AppTheme_tluc_seri_ambr
            color_pump -> R.style.AppTheme_tluc_seri_pump
            color_redx -> R.style.AppTheme_tluc_seri_redx
            color_lila -> R.style.AppTheme_tluc_seri_lila
            color_blue -> R.style.AppTheme_tluc_seri_blue
            color_cyan -> R.style.AppTheme_tluc_seri_cyan
            else -> R.style.AppTheme_tluc_seri_achr
        }
        font_mono -> when (color) {
            color_ambr -> R.style.AppTheme_tluc_mono_ambr
            color_pump -> R.style.AppTheme_tluc_mono_pump
            color_redx -> R.style.AppTheme_tluc_mono_redx
            color_lila -> R.style.AppTheme_tluc_mono_lila
            color_blue -> R.style.AppTheme_tluc_mono_blue
            color_cyan -> R.style.AppTheme_tluc_mono_cyan
            else -> R.style.AppTheme_tluc_mono_achr
        }
        font_curs -> when (color) {
            color_ambr -> R.style.AppTheme_tluc_curs_ambr
            color_pump -> R.style.AppTheme_tluc_curs_pump
            color_redx -> R.style.AppTheme_tluc_curs_redx
            color_lila -> R.style.AppTheme_tluc_curs_lila
            color_blue -> R.style.AppTheme_tluc_curs_blue
            color_cyan -> R.style.AppTheme_tluc_curs_cyan
            else -> R.style.AppTheme_tluc_curs_achr
        }
        font_ubun -> when (color) {
            color_ambr -> R.style.AppTheme_tluc_ubun_ambr
            color_pump -> R.style.AppTheme_tluc_ubun_pump
            color_redx -> R.style.AppTheme_tluc_ubun_redx
            color_lila -> R.style.AppTheme_tluc_ubun_lila
            color_blue -> R.style.AppTheme_tluc_ubun_blue
            color_cyan -> R.style.AppTheme_tluc_ubun_cyan
            else -> R.style.AppTheme_tluc_ubun_achr
        }
        else -> when (color) {
            color_ambr -> R.style.AppTheme_tluc_sans_ambr
            color_pump -> R.style.AppTheme_tluc_sans_pump
            color_redx -> R.style.AppTheme_tluc_sans_redx
            color_lila -> R.style.AppTheme_tluc_sans_lila
            color_blue -> R.style.AppTheme_tluc_sans_blue
            color_cyan -> R.style.AppTheme_tluc_sans_cyan
            else -> R.style.AppTheme_tluc_sans_achr
        }
    }
    back_tpar -> when (font) {
        font_seri -> when (color) {
            color_ambr -> R.style.AppTheme_tpar_seri_ambr
            color_pump -> R.style.AppTheme_tpar_seri_pump
            color_redx -> R.style.AppTheme_tpar_seri_redx
            color_lila -> R.style.AppTheme_tpar_seri_lila
            color_blue -> R.style.AppTheme_tpar_seri_blue
            color_cyan -> R.style.AppTheme_tpar_seri_cyan
            else -> R.style.AppTheme_tpar_seri_achr
        }
        font_mono -> when (color) {
            color_ambr -> R.style.AppTheme_tpar_mono_ambr
            color_pump -> R.style.AppTheme_tpar_mono_pump
            color_redx -> R.style.AppTheme_tpar_mono_redx
            color_lila -> R.style.AppTheme_tpar_mono_lila
            color_blue -> R.style.AppTheme_tpar_mono_blue
            color_cyan -> R.style.AppTheme_tpar_mono_cyan
            else -> R.style.AppTheme_tpar_mono_achr
        }
        font_curs -> when (color) {
            color_ambr -> R.style.AppTheme_tpar_curs_ambr
            color_pump -> R.style.AppTheme_tpar_curs_pump
            color_redx -> R.style.AppTheme_tpar_curs_redx
            color_lila -> R.style.AppTheme_tpar_curs_lila
            color_blue -> R.style.AppTheme_tpar_curs_blue
            color_cyan -> R.style.AppTheme_tpar_curs_cyan
            else -> R.style.AppTheme_tpar_curs_achr
        }
        font_ubun -> when (color) {
            color_ambr -> R.style.AppTheme_tpar_ubun_ambr
            color_pump -> R.style.AppTheme_tpar_ubun_pump
            color_redx -> R.style.AppTheme_tpar_ubun_redx
            color_lila -> R.style.AppTheme_tpar_ubun_lila
            color_blue -> R.style.AppTheme_tpar_ubun_blue
            color_cyan -> R.style.AppTheme_tpar_ubun_cyan
            else -> R.style.AppTheme_tpar_ubun_achr
        }
        else -> when (color) {
            color_ambr -> R.style.AppTheme_tpar_sans_ambr
            color_pump -> R.style.AppTheme_tpar_sans_pump
            color_redx -> R.style.AppTheme_tpar_sans_redx
            color_lila -> R.style.AppTheme_tpar_sans_lila
            color_blue -> R.style.AppTheme_tpar_sans_blue
            color_cyan -> R.style.AppTheme_tpar_sans_cyan
            else -> R.style.AppTheme_tpar_sans_achr
        }
    }
    else -> when (font) {
        font_seri -> when (color) {
            color_ambr -> R.style.AppTheme_opaq_seri_ambr
            color_pump -> R.style.AppTheme_opaq_seri_pump
            color_redx -> R.style.AppTheme_opaq_seri_redx
            color_lila -> R.style.AppTheme_opaq_seri_lila
            color_blue -> R.style.AppTheme_opaq_seri_blue
            color_cyan -> R.style.AppTheme_opaq_seri_cyan
            else -> R.style.AppTheme_opaq_seri_achr
        }
        font_mono -> when (color) {
            color_ambr -> R.style.AppTheme_opaq_mono_ambr
            color_pump -> R.style.AppTheme_opaq_mono_pump
            color_redx -> R.style.AppTheme_opaq_mono_redx
            color_lila -> R.style.AppTheme_opaq_mono_lila
            color_blue -> R.style.AppTheme_opaq_mono_blue
            color_cyan -> R.style.AppTheme_opaq_mono_cyan
            else -> R.style.AppTheme_opaq_mono_achr
        }
        font_curs -> when (color) {
            color_ambr -> R.style.AppTheme_opaq_curs_ambr
            color_pump -> R.style.AppTheme_opaq_curs_pump
            color_redx -> R.style.AppTheme_opaq_curs_redx
            color_lila -> R.style.AppTheme_opaq_curs_lila
            color_blue -> R.style.AppTheme_opaq_curs_blue
            color_cyan -> R.style.AppTheme_opaq_curs_cyan
            else -> R.style.AppTheme_opaq_curs_achr
        }
        font_ubun -> when (color) {
            color_ambr -> R.style.AppTheme_opaq_ubun_ambr
            color_pump -> R.style.AppTheme_opaq_ubun_pump
            color_redx -> R.style.AppTheme_opaq_ubun_redx
            color_lila -> R.style.AppTheme_opaq_ubun_lila
            color_blue -> R.style.AppTheme_opaq_ubun_blue
            color_cyan -> R.style.AppTheme_opaq_ubun_cyan
            else -> R.style.AppTheme_opaq_ubun_achr
        }
        else -> when (color) {
            color_ambr -> R.style.AppTheme_opaq_sans_ambr
            color_pump -> R.style.AppTheme_opaq_sans_pump
            color_redx -> R.style.AppTheme_opaq_sans_redx
            color_lila -> R.style.AppTheme_opaq_sans_lila
            color_blue -> R.style.AppTheme_opaq_sans_blue
            color_cyan -> R.style.AppTheme_opaq_sans_cyan
            else -> R.style.AppTheme_opaq_sans_achr
        }
    }
}
